export const SET_NOMINATED_MOVIE= 'SET_NOMINATED_MOVIE'
export const REMOVE_MOVIE = 'REMOVE_MOVIE'

export const NOMINATE_MOVIE = 'NOMINATE_MOVIE'
export const SEARCH_MOVIE ='SEARCH_MOVIE'
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS"
export const SEARCH_MOVIE_FAILED = "SEARCH_MOVIE_FAILED"
export const SET_MOVIES= "SET_MOVIES"